"""empty message

Revision ID: fd99dc0581bc
Revises: 
Create Date: 2025-04-18 23:49:52.306753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd99dc0581bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailTemplates',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('type', sa.SMALLINT(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('managers',
    sa.Column('role', sa.Enum('manager', 'main_manager', 'admin', name='role'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('second_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('news',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('publish_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('client_type', sa.Enum('individ', 'legal_entitie', name='clienttype'), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('second_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('inn', sa.String(length=10), nullable=True),
    sa.Column('create_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modify_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('newsContents',
    sa.Column('news_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modify_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsContents')
    op.drop_table('clients')
    op.drop_table('news')
    op.drop_table('managers')
    op.drop_table('emailTemplates')
    # ### end Alembic commands ###
